
name: P519-Workflow

on:
  push:
    branches:  [master]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: [windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup-MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.2.0

      - name: Restore NuGet packages
        run: nuget restore P519.sln

      - name: Build project
        run: msbuild P519.sln

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          name: P519-Import
          # A file, directory or wildcard pattern that describes what to upload
          path: P519-Import/bin/Debug/*.*
